# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckerUI-MainWindow.ui',
# licensing of 'CheckerUI-MainWindow.ui' applies.
#
# Created: Mon Feb  8 20:41:42 2021
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 700))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lyt_verticalLayout_global = QtWidgets.QVBoxLayout()
        self.lyt_verticalLayout_global.setObjectName("lyt_verticalLayout_global")
        self.lyt_horizontalLayout_rulesTitle = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_rulesTitle.setObjectName("lyt_horizontalLayout_rulesTitle")
        self.lab_rulesTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_rulesTitle.sizePolicy().hasHeightForWidth())
        self.lab_rulesTitle.setSizePolicy(sizePolicy)
        self.lab_rulesTitle.setObjectName("lab_rulesTitle")
        self.lyt_horizontalLayout_rulesTitle.addWidget(self.lab_rulesTitle)
        self.lab_rulesPath = QtWidgets.QLabel(self.centralwidget)
        self.lab_rulesPath.setObjectName("lab_rulesPath")
        self.lyt_horizontalLayout_rulesTitle.addWidget(self.lab_rulesPath)
        self.btn_rulesPathBrowse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rulesPathBrowse.sizePolicy().hasHeightForWidth())
        self.btn_rulesPathBrowse.setSizePolicy(sizePolicy)
        self.btn_rulesPathBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_rulesPathBrowse.setObjectName("btn_rulesPathBrowse")
        self.lyt_horizontalLayout_rulesTitle.addWidget(self.btn_rulesPathBrowse)
        self.lyt_verticalLayout_global.addLayout(self.lyt_horizontalLayout_rulesTitle)
        self.lyt_horizontalLayout_rulesList = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_rulesList.setObjectName("lyt_horizontalLayout_rulesList")
        self.scrollArea_rulesList = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_rulesList.setWidgetResizable(True)
        self.scrollArea_rulesList.setObjectName("scrollArea_rulesList")
        self.scrollAreaWidgetContents_rulesList = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_rulesList.setGeometry(QtCore.QRect(0, 0, 576, 256))
        self.scrollAreaWidgetContents_rulesList.setObjectName("scrollAreaWidgetContents_rulesList")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_rulesList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_rulesList.setWidget(self.scrollAreaWidgetContents_rulesList)
        self.lyt_horizontalLayout_rulesList.addWidget(self.scrollArea_rulesList)
        self.lyt_verticalLayout_global.addLayout(self.lyt_horizontalLayout_rulesList)
        self.lyt_horizontalLayout_rulesActions = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_rulesActions.setObjectName("lyt_horizontalLayout_rulesActions")
        self.btn_addRule = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addRule.sizePolicy().hasHeightForWidth())
        self.btn_addRule.setSizePolicy(sizePolicy)
        self.btn_addRule.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_addRule.setObjectName("btn_addRule")
        self.lyt_horizontalLayout_rulesActions.addWidget(self.btn_addRule)
        self.btn_checkRules = QtWidgets.QPushButton(self.centralwidget)
        self.btn_checkRules.setObjectName("btn_checkRules")
        self.lyt_horizontalLayout_rulesActions.addWidget(self.btn_checkRules)
        self.btn_fixRules = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fixRules.setObjectName("btn_fixRules")
        self.lyt_horizontalLayout_rulesActions.addWidget(self.btn_fixRules)
        self.btn_deleteRules = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_deleteRules.sizePolicy().hasHeightForWidth())
        self.btn_deleteRules.setSizePolicy(sizePolicy)
        self.btn_deleteRules.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_deleteRules.setObjectName("btn_deleteRules")
        self.lyt_horizontalLayout_rulesActions.addWidget(self.btn_deleteRules)
        self.lyt_verticalLayout_global.addLayout(self.lyt_horizontalLayout_rulesActions)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.lyt_verticalLayout_global.addItem(spacerItem)
        self.middleSeparatorLine = QtWidgets.QFrame(self.centralwidget)
        self.middleSeparatorLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.middleSeparatorLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.middleSeparatorLine.setObjectName("middleSeparatorLine")
        self.lyt_verticalLayout_global.addWidget(self.middleSeparatorLine)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.lyt_verticalLayout_global.addItem(spacerItem1)
        self.lyt_horizontalLayout_scriptsList = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_scriptsList.setObjectName("lyt_horizontalLayout_scriptsList")
        self.lyt_verticalLayout_preScripts = QtWidgets.QVBoxLayout()
        self.lyt_verticalLayout_preScripts.setObjectName("lyt_verticalLayout_preScripts")
        self.lyt_horizontalLayout_preScripts = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_preScripts.setObjectName("lyt_horizontalLayout_preScripts")
        self.lab_preScriptsTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_preScriptsTitle.sizePolicy().hasHeightForWidth())
        self.lab_preScriptsTitle.setSizePolicy(sizePolicy)
        self.lab_preScriptsTitle.setObjectName("lab_preScriptsTitle")
        self.lyt_horizontalLayout_preScripts.addWidget(self.lab_preScriptsTitle)
        self.lab_preScriptsPath = QtWidgets.QLabel(self.centralwidget)
        self.lab_preScriptsPath.setObjectName("lab_preScriptsPath")
        self.lyt_horizontalLayout_preScripts.addWidget(self.lab_preScriptsPath)
        self.btn_preScriptsPathBrowse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_preScriptsPathBrowse.sizePolicy().hasHeightForWidth())
        self.btn_preScriptsPathBrowse.setSizePolicy(sizePolicy)
        self.btn_preScriptsPathBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_preScriptsPathBrowse.setObjectName("btn_preScriptsPathBrowse")
        self.lyt_horizontalLayout_preScripts.addWidget(self.btn_preScriptsPathBrowse)
        self.lyt_verticalLayout_preScripts.addLayout(self.lyt_horizontalLayout_preScripts)
        self.scrollArea_preScripts = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_preScripts.setWidgetResizable(True)
        self.scrollArea_preScripts.setObjectName("scrollArea_preScripts")
        self.scrollAreaWidgetContents_preScripts = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_preScripts.setGeometry(QtCore.QRect(0, 0, 274, 223))
        self.scrollAreaWidgetContents_preScripts.setObjectName("scrollAreaWidgetContents_preScripts")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_preScripts)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_preScripts.setWidget(self.scrollAreaWidgetContents_preScripts)
        self.lyt_verticalLayout_preScripts.addWidget(self.scrollArea_preScripts)
        self.lyt_horizontalLayout_scriptsList.addLayout(self.lyt_verticalLayout_preScripts)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.lyt_horizontalLayout_scriptsList.addItem(spacerItem2)
        self.lyt_verticalLayout_postScripts = QtWidgets.QVBoxLayout()
        self.lyt_verticalLayout_postScripts.setObjectName("lyt_verticalLayout_postScripts")
        self.lyt_horizontalLayout_postScripts = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_postScripts.setObjectName("lyt_horizontalLayout_postScripts")
        self.lab_postScriptsTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_postScriptsTitle.sizePolicy().hasHeightForWidth())
        self.lab_postScriptsTitle.setSizePolicy(sizePolicy)
        self.lab_postScriptsTitle.setObjectName("lab_postScriptsTitle")
        self.lyt_horizontalLayout_postScripts.addWidget(self.lab_postScriptsTitle)
        self.lab_postScriptsPath = QtWidgets.QLabel(self.centralwidget)
        self.lab_postScriptsPath.setObjectName("lab_postScriptsPath")
        self.lyt_horizontalLayout_postScripts.addWidget(self.lab_postScriptsPath)
        self.btn_postScriptsPathBrowse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_postScriptsPathBrowse.sizePolicy().hasHeightForWidth())
        self.btn_postScriptsPathBrowse.setSizePolicy(sizePolicy)
        self.btn_postScriptsPathBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_postScriptsPathBrowse.setObjectName("btn_postScriptsPathBrowse")
        self.lyt_horizontalLayout_postScripts.addWidget(self.btn_postScriptsPathBrowse)
        self.lyt_verticalLayout_postScripts.addLayout(self.lyt_horizontalLayout_postScripts)
        self.scrollArea_postScripts = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_postScripts.setWidgetResizable(True)
        self.scrollArea_postScripts.setObjectName("scrollArea_postScripts")
        self.scrollAreaWidgetContents_postScripts = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_postScripts.setGeometry(QtCore.QRect(0, 0, 274, 223))
        self.scrollAreaWidgetContents_postScripts.setObjectName("scrollAreaWidgetContents_postScripts")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_postScripts)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_postScripts.setWidget(self.scrollAreaWidgetContents_postScripts)
        self.lyt_verticalLayout_postScripts.addWidget(self.scrollArea_postScripts)
        self.lyt_horizontalLayout_scriptsList.addLayout(self.lyt_verticalLayout_postScripts)
        self.lyt_verticalLayout_global.addLayout(self.lyt_horizontalLayout_scriptsList)
        self.lyt_horizontalLayout_scriptsActions = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_scriptsActions.setObjectName("lyt_horizontalLayout_scriptsActions")
        self.btn_log = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_log.sizePolicy().hasHeightForWidth())
        self.btn_log.setSizePolicy(sizePolicy)
        self.btn_log.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_log.setObjectName("btn_log")
        self.lyt_horizontalLayout_scriptsActions.addWidget(self.btn_log)
        self.btn_saveScene = QtWidgets.QPushButton(self.centralwidget)
        self.btn_saveScene.setObjectName("btn_saveScene")
        self.lyt_horizontalLayout_scriptsActions.addWidget(self.btn_saveScene)
        self.btn_exportSelected = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exportSelected.sizePolicy().hasHeightForWidth())
        self.btn_exportSelected.setSizePolicy(sizePolicy)
        self.btn_exportSelected.setObjectName("btn_exportSelected")
        self.lyt_horizontalLayout_scriptsActions.addWidget(self.btn_exportSelected)
        self.btn_exportSettings = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exportSettings.sizePolicy().hasHeightForWidth())
        self.btn_exportSettings.setSizePolicy(sizePolicy)
        self.btn_exportSettings.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_exportSettings.setObjectName("btn_exportSettings")
        self.lyt_horizontalLayout_scriptsActions.addWidget(self.btn_exportSettings)
        self.lyt_verticalLayout_global.addLayout(self.lyt_horizontalLayout_scriptsActions)
        self.verticalLayout_3.addLayout(self.lyt_verticalLayout_global)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionChange_Dir = QtWidgets.QAction(MainWindow)
        self.actionChange_Dir.setObjectName("actionChange_Dir")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lab_rulesTitle.setText(QtWidgets.QApplication.translate("MainWindow", "Rule Set:", None, -1))
        self.lab_rulesPath.setText(QtWidgets.QApplication.translate("MainWindow", "C:/Example/Path/To/Rules/Max", None, -1))
        self.btn_rulesPathBrowse.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_addRule.setText(QtWidgets.QApplication.translate("MainWindow", "Add Rule", None, -1))
        self.btn_checkRules.setText(QtWidgets.QApplication.translate("MainWindow", "Check All", None, -1))
        self.btn_fixRules.setText(QtWidgets.QApplication.translate("MainWindow", "Fix All", None, -1))
        self.btn_deleteRules.setText(QtWidgets.QApplication.translate("MainWindow", "Delete All", None, -1))
        self.lab_preScriptsTitle.setText(QtWidgets.QApplication.translate("MainWindow", "Pre-Scripts:", None, -1))
        self.lab_preScriptsPath.setText(QtWidgets.QApplication.translate("MainWindow", "C:/Example/Path/To/PreScripts", None, -1))
        self.btn_preScriptsPathBrowse.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.lab_postScriptsTitle.setText(QtWidgets.QApplication.translate("MainWindow", "Post-Scripts:", None, -1))
        self.lab_postScriptsPath.setText(QtWidgets.QApplication.translate("MainWindow", "C:/Example/Path/To/PostScripts", None, -1))
        self.btn_postScriptsPathBrowse.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_log.setText(QtWidgets.QApplication.translate("MainWindow", "Show Log", None, -1))
        self.btn_saveScene.setText(QtWidgets.QApplication.translate("MainWindow", "Save Scene", None, -1))
        self.btn_exportSelected.setText(QtWidgets.QApplication.translate("MainWindow", "Export Selected", None, -1))
        self.btn_exportSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Export Settings", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.actionChange_Dir.setText(QtWidgets.QApplication.translate("MainWindow", "Change Dir", None, -1))

