# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckerUI-RuleSettings.ui',
# licensing of 'CheckerUI-RuleSettings.ui' applies.
#
# Created: Mon Feb  8 20:41:42 2021
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(550, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lyt_horizontalLayout_ruleName = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_ruleName.setObjectName("lyt_horizontalLayout_ruleName")
        self.lab_ruleName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_ruleName.sizePolicy().hasHeightForWidth())
        self.lab_ruleName.setSizePolicy(sizePolicy)
        self.lab_ruleName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lab_ruleName.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_ruleName.setObjectName("lab_ruleName")
        self.lyt_horizontalLayout_ruleName.addWidget(self.lab_ruleName)
        self.txt_ruleName = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ruleName.sizePolicy().hasHeightForWidth())
        self.txt_ruleName.setSizePolicy(sizePolicy)
        self.txt_ruleName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txt_ruleName.setObjectName("txt_ruleName")
        self.lyt_horizontalLayout_ruleName.addWidget(self.txt_ruleName)
        self.verticalLayout_2.addLayout(self.lyt_horizontalLayout_ruleName)
        self.lyt_horizontalLayout_ruleDesc = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_ruleDesc.setObjectName("lyt_horizontalLayout_ruleDesc")
        self.lab_ruleDesc = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_ruleDesc.sizePolicy().hasHeightForWidth())
        self.lab_ruleDesc.setSizePolicy(sizePolicy)
        self.lab_ruleDesc.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lab_ruleDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_ruleDesc.setObjectName("lab_ruleDesc")
        self.lyt_horizontalLayout_ruleDesc.addWidget(self.lab_ruleDesc)
        self.txt_ruleDesc = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ruleDesc.sizePolicy().hasHeightForWidth())
        self.txt_ruleDesc.setSizePolicy(sizePolicy)
        self.txt_ruleDesc.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txt_ruleDesc.setObjectName("txt_ruleDesc")
        self.lyt_horizontalLayout_ruleDesc.addWidget(self.txt_ruleDesc)
        self.verticalLayout_2.addLayout(self.lyt_horizontalLayout_ruleDesc)
        self.middleSeparatorLine = QtWidgets.QFrame(self.centralwidget)
        self.middleSeparatorLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.middleSeparatorLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.middleSeparatorLine.setObjectName("middleSeparatorLine")
        self.verticalLayout_2.addWidget(self.middleSeparatorLine)
        self.lyt_horizontalLayout_ruleCode = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_ruleCode.setObjectName("lyt_horizontalLayout_ruleCode")
        self.lyt_verticalLayout_checkCode = QtWidgets.QVBoxLayout()
        self.lyt_verticalLayout_checkCode.setObjectName("lyt_verticalLayout_checkCode")
        self.lyt_horizontalLayout_checkCode = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_checkCode.setObjectName("lyt_horizontalLayout_checkCode")
        self.lab_checkCode = QtWidgets.QLabel(self.centralwidget)
        self.lab_checkCode.setObjectName("lab_checkCode")
        self.lyt_horizontalLayout_checkCode.addWidget(self.lab_checkCode)
        self.cmb_checkCode = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_checkCode.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmb_checkCode.setObjectName("cmb_checkCode")
        self.cmb_checkCode.addItem("")
        self.cmb_checkCode.addItem("")
        self.cmb_checkCode.addItem("")
        self.lyt_horizontalLayout_checkCode.addWidget(self.cmb_checkCode)
        self.btn_ruleCheckBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ruleCheckBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_ruleCheckBrowse.setObjectName("btn_ruleCheckBrowse")
        self.lyt_horizontalLayout_checkCode.addWidget(self.btn_ruleCheckBrowse)
        self.lyt_verticalLayout_checkCode.addLayout(self.lyt_horizontalLayout_checkCode)
        self.txt_checkCode = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_checkCode.sizePolicy().hasHeightForWidth())
        self.txt_checkCode.setSizePolicy(sizePolicy)
        self.txt_checkCode.setObjectName("txt_checkCode")
        self.lyt_verticalLayout_checkCode.addWidget(self.txt_checkCode)
        self.lyt_horizontalLayout_ruleCode.addLayout(self.lyt_verticalLayout_checkCode)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.lyt_horizontalLayout_ruleCode.addItem(spacerItem)
        self.lyt_verticalLayout_fixCode = QtWidgets.QVBoxLayout()
        self.lyt_verticalLayout_fixCode.setObjectName("lyt_verticalLayout_fixCode")
        self.lyt_horizontalLayout_fixCode = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_fixCode.setObjectName("lyt_horizontalLayout_fixCode")
        self.lab_fixCode = QtWidgets.QLabel(self.centralwidget)
        self.lab_fixCode.setObjectName("lab_fixCode")
        self.lyt_horizontalLayout_fixCode.addWidget(self.lab_fixCode)
        self.cmb_fixCode = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_fixCode.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmb_fixCode.setObjectName("cmb_fixCode")
        self.cmb_fixCode.addItem("")
        self.cmb_fixCode.addItem("")
        self.cmb_fixCode.addItem("")
        self.lyt_horizontalLayout_fixCode.addWidget(self.cmb_fixCode)
        self.btn_ruleFixBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ruleFixBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_ruleFixBrowse.setObjectName("btn_ruleFixBrowse")
        self.lyt_horizontalLayout_fixCode.addWidget(self.btn_ruleFixBrowse)
        self.lyt_verticalLayout_fixCode.addLayout(self.lyt_horizontalLayout_fixCode)
        self.txt_fixCode = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_fixCode.setObjectName("txt_fixCode")
        self.lyt_verticalLayout_fixCode.addWidget(self.txt_fixCode)
        self.lyt_horizontalLayout_ruleCode.addLayout(self.lyt_verticalLayout_fixCode)
        self.verticalLayout_2.addLayout(self.lyt_horizontalLayout_ruleCode)
        self.lyt_horizontalLayout_ruleButton = QtWidgets.QHBoxLayout()
        self.lyt_horizontalLayout_ruleButton.setObjectName("lyt_horizontalLayout_ruleButton")
        self.btn_ruleCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ruleCreate.setObjectName("btn_ruleCreate")
        self.lyt_horizontalLayout_ruleButton.addWidget(self.btn_ruleCreate)
        self.verticalLayout_2.addLayout(self.lyt_horizontalLayout_ruleButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lab_ruleName.setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.lab_ruleDesc.setText(QtWidgets.QApplication.translate("MainWindow", "Description", None, -1))
        self.lab_checkCode.setText(QtWidgets.QApplication.translate("MainWindow", "Rule Check Functiion", None, -1))
        self.cmb_checkCode.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Python", None, -1))
        self.cmb_checkCode.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "MaxScript", None, -1))
        self.cmb_checkCode.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MEL", None, -1))
        self.btn_ruleCheckBrowse.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.lab_fixCode.setText(QtWidgets.QApplication.translate("MainWindow", "Rule Fix Function (Optional)", None, -1))
        self.cmb_fixCode.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Python", None, -1))
        self.cmb_fixCode.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "MaxScript", None, -1))
        self.cmb_fixCode.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "MEL", None, -1))
        self.btn_ruleFixBrowse.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_ruleCreate.setText(QtWidgets.QApplication.translate("MainWindow", "Save Rule", None, -1))

